export const referenceSources = {
  "accounts-v2": "v2/core/accounts",
  "account-links-v2": "v2/core/account-links",
  "account-tokens-v2": "v2/core/account-tokens",
  balance: "balance",
  "balance-transactions": "balance_transactions",
  charges: "charges",
  customers: "customers",
  "customer-session": "customer_sessions",
  disputes: "disputes",
  "events-v1": "events",
  "events-v2": "v2/core/events",
  "event-destinations-v2": "v2/core/event-destinations",
  files: "files",
  "file-links": "file_links",
  mandates: "mandates",
  "payment-intents": "payment_intents",
  "persons-v2": "v2/core/persons",
  "person-tokens-v2": "v2/core/person-tokens",
  "setup-intents": "setup_intents",
  "setup-attempts": "setup_attempts",
  "stripe-balance-debit-agreement": "stripe_balance_debit_agreements",
  payouts: "payouts",
  refunds: "refunds",
  "confirmation-token": "confirmation_tokens",
  tokens: "tokens",
  "payment-methods": "payment_methods",
  "payment-method-configurations": "payment_method_configurations",
  "payment-method-domains": "payment_method_domains",
  "bank-accounts": "customer_bank_accounts",
  "cash-balance": "cash_balance",
  "cash-balance-transactions": "cash_balance_transactions",
  cards: "cards",
  sources: "sources",
};

export const objectSourceOverrides = {
  balance: "balance/balance_object",
};
